language: objective-c
osx_image: xcode7.3
xcode_project: CasperSplash.xcodeproj
xcode_scheme: CasperSplash
xcode_sdk: macosx10.11

script:
- xcodebuild build test -project CasperSplash.xcodeproj -scheme CasperSplash